# Generated by Django 5.0 on 2023-12-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_planners_options_periodevents_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planners',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='periodevents',
            name='name',
        ),
    ]
